<?php

namespace ContainerSDW2pxn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V3AtR_3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v3AtR.3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v3AtR.3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.v3AtR.3.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.v3AtR.3": it references class "App\\Entity\\Article" but no such service exists.'],
            'cartService' => ['privates', 'App\\Service\\Cart\\CartService', 'getCartServiceService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'article' => 'App\\Entity\\Article',
            'cartService' => 'App\\Service\\Cart\\CartService',
            'manager' => '?',
        ]);
    }
}
