<?php

namespace ContainerSDW2pxn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SbvMfphService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sbvMfph' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sbvMfph'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cartService' => ['privates', 'App\\Service\\Cart\\CartService', 'getCartServiceService', true],
        ], [
            'cartService' => 'App\\Service\\Cart\\CartService',
        ]);
    }
}
