<?php

namespace ContainerSDW2pxn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QeJC6eJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QeJC6eJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QeJC6eJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.QeJC6eJ.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.QeJC6eJ": it references class "App\\Entity\\Article" but no such service exists.'],
            'favorisRepository' => ['privates', 'App\\Repository\\FavorisRepository', 'getFavorisRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'article' => 'App\\Entity\\Article',
            'favorisRepository' => 'App\\Repository\\FavorisRepository',
            'manager' => '?',
        ]);
    }
}
