<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK17LlZb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK17LlZb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK17LlZb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK17LlZb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK17LlZb\App_KernelDevDebugContainer([
    'container.build_hash' => 'K17LlZb',
    'container.build_id' => 'd64861a9',
    'container.build_time' => 1644345633,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK17LlZb');
