<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP0CJPbY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP0CJPbY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP0CJPbY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP0CJPbY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP0CJPbY\App_KernelDevDebugContainer([
    'container.build_hash' => 'P0CJPbY',
    'container.build_id' => 'be250fc7',
    'container.build_time' => 1643211815,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP0CJPbY');
